//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroDayWizard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZeroDayWizard.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to key, comment
        ///Incl.Keygen, 包含有注册器
        ///keygen only, 只含注册器
        ///WinALL, 适用于所有版本Windows操作系统（一般是指95 98 ME 2000 XP 2003）
        ///Trainer, 密技
        ///Cracked, 破解版本（对原文件进行了修改）
        ///MACOSX, Macintosh平台上的软件
        ///NUKED, 发布的内容违犯规则或存在问题因而被取消，别的小组可重新发布。
        ///Ebook, 电子书
        ///Repack, 重新打包(对上一个不成功的破解的修正)
        ///Proper, 正确的(对上一个不成功的破解的修正)
        ///Plug in, 插件
        ///regged, 已經注册了的軟件
        ///retail, 零售版
        ///READ.NFO, 一般表示有某种特别说明
        ///DIRFIX nfo, 说明文件修正，一般只有一个nfo文件
        ///BiLiNGUAL, 双语版本
        ///MutilLiNGUAL, 多语言版本
        ///PHP.NULL, PHP完整脚本程序
        ///ASP.NULL, ASP完整脚本程序
        ///Incl.Patch, 带有破解补丁
        ///WORKING, 先前已有组织释放，但是不能完整工作，当前的释 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ContentType {
            get {
                return ResourceManager.GetString("ContentType", resourceCulture);
            }
        }
    }
}
